stages:
  - test
  - build
  - delivery
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH:$CI_COMMIT_SHORT_SHA

unit-test:
  stage: test
  image: node:14.16.1-alpine
  script:
    - yarn
    - yarn test
  environment:
    name: staging
  only:
    - merge_requests
  tags:
    - k8s-stg-runner

build-delivery-staging:
  stage: build
  image: docker/compose:latest
  services:
    - name: docker:18.09.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker-compose build
    - docker tag $TAG_LATEST $TAG_COMMIT
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  environment:
    name: staging
  only:
    - staging
  tags:
    - k8s-stg-runner

deploy-staging:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl --kubeconfig="$KUBE_CONFIG" set image --record deployment/web-portal web-portal=$TAG_COMMIT -n integration
  environment:
    name: staging
  only:
    - staging
  tags:
    - k8s-stg-runner

build-delivery-production:
  stage: build
  image: docker/compose:latest
  services:
    - name: docker:18.09.7-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    STAGING_IMAGE: $CI_REGISTRY_IMAGE/staging:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $STAGING_IMAGE
    - docker-compose build
    - docker tag $STAGING_IMAGE $TAG_LATEST
    - docker tag $STAGING_IMAGE $TAG_COMMIT
    - docker push $TAG_LATEST
    - docker push $TAG_COMMIT
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  environment:
    name: production
  only:
    - production
  tags:
    - k8s-prd-runner

deploy-production:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl --kubeconfig="$KUBE_CONFIG" set image --record deployment/web-portal web-portal=$TAG_COMMIT -n integration
  environment:
    name: production
  only:
    - production
  tags:
    - k8s-prd-runner
  when: manual
