version: '3.0'

services:
  ssi-web-portal:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_HOST: 0.0.0.0
        APP_PORT: 8080
        APP_BASE_API: ${APP_BASE_API}
        APP_PREFIX: ${APP_PREFIX}
    image: ssi-registry.teda.th/ssi/web-portal/staging:latest
    container_name: ssi-web-portal
    restart: always
    ports:
      - 8000:8080
